name: dart_analysis
description: A command-line tool to find unused files in a Dart/Flutter project.
version: 0.0.1

environment:
  sdk: ^3.8.1

executables:
  dart_analysis:

dependencies:
  analyzer: ^6.4.1
  interact_cli: ^2.4.0
  path: ^1.9.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
